config/routes.rb
FbEvents::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: 'sessions#failure'
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :events, only: [:index]
  get 'rate', controller: :events

  get 'sync_fb_event_members', controller: :background
  get 'sync_fb_events', controller: :background
  get 'count_event_members', controller: :background

  root to: 'events#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/event.rb
class Event < ActiveRecord::Base

  User.all.each do |u|
    define_singleton_method ["scope","for","user",u.id].join("_") do
      u.events
    end
  end

  belongs_to :user
  validates_presence_of :user

  def self.scopes
    User.all.map &:name.to_sym
  end

  def attendence_ratio
    all_rsvp.to_f/all_members_count.to_f rescue 0
  end

  def local_attendence_ratio
    friends_rsvp.to_f/all_rsvp.to_f rescue 0
  end

  def ratio
    # local_attendence_ratio + (attendence_ratio * 0.01)
    friends_rsvp or 0
  end

  def facebook_url
    "https://www.facebook.com/events/#{eid}"
  end

  def rated user
    @tmp_rate ||= Rate.where(event_id: id, user_id: user.id).first.rating rescue 0
  end

  def rated? n, user
    r = rated(user)
    n <= r
  end

  def self.count_event_members user
    user.events.each do |e|
      puts "Counting event members"
      #e.rsvp_yes = user.event_members.where(eid: e.eid, rsvp_status: 'attending').count
      #e.rsvp_maybe = user.event_members.where(eid: e.eid, rsvp_status: 'unsure').count
      e.friends_rsvp = user.event_members.where(eid: e.eid).count
      e.all_rsvp = e.attending_count + e.unsure_count
      e.save!
    end
  end

  def self.sync_fb_events user

    fql = "SELECT eid,name,attending_count,all_members_count,declined_count,not_replied_count,unsure_count
            FROM event
            WHERE eid IN(
              SELECT eid FROM event_member
              WHERE uid IN ( SELECT uid2 FROM friend WHERE uid1=me() )
              AND (rsvp_status='attending' OR rsvp_status='unsure')
            )"

    FbGraph::Query.new(fql).fetch(access_token: user.oauth_token).each do |fb_event|
      puts "Syncing event"

      event = Event.where(eid: fb_event[:eid]).first_or_initialize

      event.name = fb_event[:name]
      event.all_members_count = fb_event[:all_members_count]
      event.attending_count = fb_event[:attending_count]
      event.declined_count = fb_event[:declined_count]
      event.unsure_count = fb_event[:unsure_count]
      event.not_replied_count = fb_event[:not_replied_count]
      event.user = user

      event.save!
    end

    fql = "SELECT eid,location,start_time,end_time,pic,description,venue
            FROM event
            WHERE eid IN(
              SELECT eid FROM event_member
              WHERE uid IN ( SELECT uid2 FROM friend WHERE uid1=me() )
              AND (rsvp_status='attending' OR rsvp_status='unsure')
            )"

    FbGraph::Query.new(fql).fetch(access_token: user.oauth_token).each do |fb_event|

      event = Event.where(eid: fb_event[:eid]).first_or_initialize

      event.location = fb_event[:location]
      event.start_time = fb_event[:start_time]
      event.end_time = fb_event[:end_time]
      event.pic = fb_event[:pic]
      event.description = fb_event[:description]
      event.venue = fb_event[:venue].to_s
      event.user = user

      event.save!
    end


  end

end

app/models/event_member.rb
class EventMember < ActiveRecord::Base

  belongs_to :user

  def self.sync_fb_events user

    fql = "SELECT eid,uid,rsvp_status FROM event_member
            WHERE uid IN ( SELECT uid2 FROM friend WHERE uid1=me() )
            AND (rsvp_status='attending' OR rsvp_status='unsure')"

    FbGraph::Query.new(fql).fetch(access_token: user.oauth_token).each do |fb_event|
      puts "Syncing member"
      event_member = EventMember.where(eid: fb_event[:eid], uid: fb_event[:uid]).first_or_initialize

      event_member.eid = fb_event[:eid]
      event_member.uid = fb_event[:uid]
      event_member.rsvp_status = fb_event[:rsvp_status]
      event_member.user = user

      event_member.save!
    end

  end
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

  def self.average_anwsers_by_user
    responses_array = Rate.distinct.count(group: :user_id).map{|r| r[1]}
    responses_array.sum / User.all.count.to_f
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :events
  has_many :event_members

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/background_controller.rb
class BackgroundController < ApplicationController

  # def sync
  #   user = User.find_by_id(params[:user_id])
  #   if user.present?
  #     EventMember.sync_fb_events(user)
  #     Event.sync_fb_events(user)
  #     Event.count_event_members(user)
  #     render text: "OK"
  #   else
  #     render text: "Fail"
  #   end
  # end

  def sync_fb_event_members
    user = User.find_by_id(params[:user_id])
    if user.present?
      EventMember.sync_fb_events(user)
      render text: "OK"
    else
      render text: "Fail"
    end
  end

  def sync_fb_events
    user = User.find_by_id(params[:user_id])
    if user.present?
      Event.sync_fb_events(user)
      render text: "OK"
    else
      render text: "Fail"
    end
  end

  def count_event_members
    user = User.find_by_id(params[:user_id])
    if user.present?
      Event.count_event_members(user)
      render text: "OK"
    else
      render text: "Fail"
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  expose(:events) do
    if current_user.nil?
      []
    else
      current_user.events.sort_by{|e| - e.ratio}.first(30)
    end
  end

  def index
  end

  def order
    @order ||= session[:order]
  end

  def switch_order sort
    if @order["DESC"].present?
      @order = sort
    else
      @order = sort + " DESC"
    end
  end

  def rate
    rating = params[:rating]
    eid = params[:eid]
    position = params[:position]

    rate = Rate.where(event_id: eid, user_id: current_user.id).first_or_initialize

    rate.position = position
    rate.rating = rating
    rate.save!

    flash[:notice] = "Rate saved!"
    ancor = ""

    tmp = position.to_i - 4
    if tmp > 0
      ancor = "pos-#{tmp}"
    end

    redirect_to events_path(anchor: ancor)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end

  def failure
    render text: params.to_s
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/index.html.haml
%h2
  My Events
  %small #{events.count} total


- events.each_with_index do |event, index|
  .event
    %a{name: "pos-#{index}"}
    .pic #{image_tag event.pic}
    .description
      .name
        = link_to event.name, event.facebook_url
      .time
        = Time.at(event.start_time).strftime("%d. %m. %Y at %I:%M %p")
      .location
        Location:
        <strong>#{event.location}</strong>
      .friends
        <strong>#{event.friends_rsvp} friends</strong> are going.
    .rate
      %button{type:"button",class:"btn btn-default btn-lg"}
        RATE
        %br
        - (1..5).each do |i|
          %span{eid: event.id, rating: i, position: (index+1), class: 'rate-link'}
            - if event.rated?(i, current_user)
              %span.glyphicon.glyphicon-star{id: "#{event.id}-#{i}", eid: "#{event.id}", n: "#{i}", fixed: "1"}
            - else
              %span.glyphicon.glyphicon-star-empty{id: "#{event.id}-#{i}", eid: "#{event.id}", n: "#{i}"}

    .clearfix


:javascript
  $(".glyphicon").mouseover(function() {
    eid = $(this).attr('eid')
    n = $(this).attr('n')*1
    showStars(eid,n);
  }).mouseout(function() {
    eid = $(this).attr('eid')
    n = $(this).attr('n')*1
    hideStars(eid);
  });

  $(".rate-link").click(function() {
    rating = $(this).attr('rating')*1
    eid = $(this).attr('eid')*1
    position = $(this).attr('position')*1
    setFixed(eid,rating);
    console.log(rating + ", " + eid + " ," + position)
    setRating(eid,rating,position)

  });

  function setFixed(eid,n) {
    console.log("asdf ")
    for(var i=1; i<=n; i++) {
      $("#"+eid+"-"+i).attr("fixed", "1");
    }
    for(var i=(n+1); i<=5; i++) {
      $("#"+eid+"-"+i).attr("fixed", "0");
      hideStars(eid)
    }
  }

  function hideStars(eid) {
    for(var i=1; i<=5; i++) {
      if($("#"+eid+"-"+i).attr("fixed") != "1") {
        $("#"+eid+"-"+i).removeClass("glyphicon-star").addClass("glyphicon-star-empty")
      }
    }
  }

  function showStars(eid, n) {
    for(var i=1; i<=n; i++) {
      $("#"+eid+"-"+i).removeClass("glyphicon-star-empty").addClass("glyphicon-star")
    }
  }


  function setRating(eid,rating,position) {
    $.ajax({
      type: "GET",
      url: "/rate",
      data: { rating: rating, eid: eid, position: position },
      success: function() {
        console.log("Done.")
      },
      error: function() {
        console.log("Some error.")
      }
    })
  }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= content_for?(:title) ? "FbEvents - #{yield(:title)}" : "FbEvents"

    %meta(name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no")

    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application", current_user: current_user
    = csrf_meta_tags

  %body
    .container

      %h1 Fb Events

      %p
        - if current_user
          Signed in as
          %strong
            = current_user.name
          = link_to "Sign out", signout_path, id: "sign_out"
        - else
          = link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in"

      - if current_user
        .sync
          %p
            %button.btn.btn-primary#sync Start Sync
            %span.loading.hidden
              = image_tag "loading.gif", height: '45px'
          .progress
            .progress-bar#progress{role:"progressbar", :'aria-valuenow' => "0", :'aria-valuemin' => "0", :'aria-valuemax' => "100", style: "width: 0%;"}

      #flash-display
        - flash.each do |type, msg|
          %div{:class => "alert alert-#{type == :notice ? "success" : type} fadeout", "data-dismiss" => "alert"}
            %button.close &times;
            = msg if msg.is_a?(String)



      = yield



      - if current_user
        :javascript

          var syncing = false;

          $(document).ready(function() {
            $("#sync").click(function() {
              if(!syncing) {
                setProgress(10)
                syncing = true;
                showLoading();
                syncEventMembers();
                //syncEvents();
                //countEventMembers();
              } else {
                alert("Staaph! Already syncing! Wait a moment please.")
              }
            })
          })

          function syncEventMembers() {
            $.ajax({
              type: "GET",
              url: "#{ENV['WORKER_URL']}/sync_fb_event_members",
              data: { user_id: #{current_user.id or nil} },
              success: function() {
                console.log("Done first.")
                setProgress(40)
                syncEvents();
              },
              error: function() {
                console.log("Some error first.")
                setProgress(40)
                syncEvents();
              }
            })
          }

          function syncEvents() {
            $.ajax({
              type: "GET",
              url: "#{ENV['WORKER_URL']}/sync_fb_events",
              data: { user_id: #{current_user.id or nil} },
              success: function() {
                console.log("Done second.")
                setProgress(70)
                countEventMembers();
              },
              error: function() {
                console.log("Some error 2.")
                setProgress(70)
                countEventMembers();
              }
            })
          }

          function countEventMembers() {
            $.ajax({
              type: "GET",
              url: "#{ENV['WORKER_URL']}/count_event_members",
              data: { user_id: #{current_user.id or nil} },
              success: function() {
                console.log("Done 3.")
                hideLoading();
                setProgress(100);
                document.location.reload(true);
              },
              error: function() {
                console.log("Some error 3.")
                hideLoading();
                setProgress(100);
                document.location.reload(true);
              }
            })
          }

          function showLoading() {
            $(".loading").removeClass('hidden');
          }

          function hideLoading() {
            $(".loading").addClass('hidden');
          }

          function setProgress(n) {
            $("#progress").animate({ width: (n+"%") },200);
          }